const {readFileSync}=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const test=require('node:test');
const source=readFileSync(new URL('../app.js',`file://${__filename}`),'utf8').split('$("#go").onclick=')[0];
function setup(){const fields={'#title':{value:''},'#price':{value:'350'},'#condition':{value:'.93'},'#out':{innerHTML:''}};const ctx=vm.createContext({console,Intl,URL,document:{querySelector:s=>fields[s]||null}});vm.runInContext(source,ctx);ctx.rows=[{id:'r',brand:'Rogue',model:'Echo Bike',category:'air bike',current_new_price:945},{id:'d',brand:'Concept2',model:'Model D PM5',category:'rower'},{id:'row',brand:'Concept2',model:'RowErg',category:'rower'},{id:'p',brand:'Peloton',model:'Bike',category:'indoor cycle'},{id:'plus',brand:'Peloton',model:'Bike+',category:'indoor cycle'},{id:'n',brand:'NordicTrack',model:'Commercial 1750',category:'treadmill'},{id:'k',brand:'Technogym',model:'Synchro Excite 700',category:'elliptical'}];vm.runInContext('C=rows;catalogAvailable=true;const catalogReady=Promise.resolve();',ctx);ctx.observationsFor=async()=>[];return {ctx,fields};}
test('rejects weak matches, significant suffix changes and accessories',()=>{const {ctx}=setup();for(const title of ['treadmill','rogue rack','WaterRower Classic walnut rowing machine','Technogym Kinesis Personal','Concept2 replacement chain for rowing machine PM5','Concept2 Model D PM5 broken monitor not working'])assert.equal(ctx.exactFind(title),null,title);assert.equal(ctx.exactFind('Peloton Bike').id,'p');assert.equal(ctx.exactFind('Peloton Bike+').id,'plus');});
test('strict positive currency input',()=>{const {ctx}=setup();for(const v of ['-100','1e3','abc100','1,2','',0,'Infinity','12.345'])assert.equal(ctx.parsePrice(v),0,v);assert.equal(ctx.parsePrice('$1,250.50'),1250.5);});
test('MSRP, missing model/generation, invalid prices and service failures never score',async()=>{const {ctx,fields}=setup();for(const [title,price] of [['Rogue Echo Bike','350'],['Concept2 rower PM5','350'],['Concept2 RowErg','350'],['treadmill','200'],['Rogue Echo Bike','-100'],['','350']]){fields['#title'].value=title;fields['#price'].value=price;await ctx.evaluate();assert.doesNotMatch(fields['#out'].innerHTML,/POUNCE|Grab Score|WORTH GRABBING/,title);}ctx.observationsFor=async()=>{throw Error('offline')};fields['#title'].value='Rogue Echo Bike';await ctx.evaluate();assert.match(fields['#out'].innerHTML,/could not be loaded/);});
const now=Date.parse('2026-09-26');
function sale(i,extra={}){return {id:String(i),equipment_id:'r',title:'Rogue Echo Bike',listing_url:i%2?'https://hibid.com/lot/'+i:'https://www.govdeals.com/en/asset/'+i+'/22',normalized_price:500+i*5,currency:'USD',condition:'used good fully functional',listing_status:'sold',verification_status:'verified',is_bundle:false,transaction_type:'auction_sale',match_type:'exact_model',sold_at:i%2?'2026-08-10':'2026-08-12',...extra};}
test('only sufficient independent compatible traceable evidence passes',()=>{const {ctx}=setup(),x=ctx.rows[0],rows=[1,2,3,4,5,6].map(i=>sale(i));assert.equal(ctx.reliableEvidence(rows,x,null,'good',now).enough,true);for(const extra of [{condition:'needs work'},{condition:'like new'},{listing_url:'https://maxsold.com/auction/123/bidgallery'},{listing_url:'https://trycommonplace.com/sell-item/concept2-skierg'},{currency:'EUR'},{sold_at:'2020-01-01'},{verification_status:'asking_verified'},{transaction_type:null},{title:'Rogue rack'},{match_type:'model_family'}])assert.equal(ctx.reliableEvidence(rows.map(x=>({...x,...extra})),x,null,'good',now).enough,false,JSON.stringify(extra));assert.equal(ctx.conditionClass('used like new'),'excellent');});
test('duplicate sales and single-source concentration cannot satisfy threshold',()=>{const {ctx}=setup(),x=ctx.rows[0];const rows=[1,2,3].flatMap(i=>[sale(i),sale(i,{id:'dupe'+i})]);assert.equal(ctx.reliableEvidence(rows,x,null,'good',now).comps.length,3);assert.equal(ctx.reliableEvidence(rows,x,null,'good',now).enough,false);assert.equal(ctx.reliableEvidence([1,3,5,7,9].map(i=>sale(i)),x,null,'good',now).enough,false);});
test('edited inputs invalidate in-flight valuations',async()=>{const {ctx,fields}=setup();let finish;ctx.observationsFor=()=>new Promise(r=>finish=r);fields['#title'].value='Rogue Echo Bike';const pending=ctx.evaluate();await Promise.resolve();ctx.clearResult();finish([]);await pending;assert.equal(fields['#out'].innerHTML,'');});
test('a genuinely eligible pool can score instead of an always-abstain stub',async()=>{const {ctx,fields}=setup();ctx.observationsFor=async()=>[1,2,3,4,5,6].map(i=>sale(i,{sold_at:new Date(Date.now()-(i%2+7)*86400000).toISOString()}));fields['#title'].value='Rogue Echo Bike';fields['#price'].value='100';await ctx.evaluate();assert.match(fields['#out'].innerHTML,/Grab Score/);assert.match(fields['#out'].innerHTML,/POUNCE/);assert.match(fields['#out'].innerHTML,/MIDDLE HALF OF OBSERVED SALES/);});
test('Concept2 evidence cannot cross explicit monitor or frame identity',()=>{const {ctx}=setup();const x=ctx.rows[1],match=ctx.concept2Match('Concept2 Model D PM5');const rows=[1,2,3,4,5,6].map(i=>sale(i,{equipment_id:'d',title:'Concept2 Model D PM3'}));assert.equal(ctx.reliableEvidence(rows,x,match,'good',now).enough,false);});
